services:
  - type: web
    name: gmes-microcredit
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: gmes_database
          property: connectionString
      - key: SECRET_KEY
        generateValue: true

databases:
  - name: gmes_database
    plan: free
    databaseName: gmes_microcredit
    user: gmes_user